# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Albconv < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/okkun-sh/albconv/releases/download/v0.1.0/albconv_Darwin_arm64.tar.gz"
      sha256 "84c32679d0177816e2330ade5fd8d92e7755605754ddcd5e040f1233f664f0f6"

      def install
        bin.install "albconv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/okkun-sh/albconv/releases/download/v0.1.0/albconv_Darwin_x86_64.tar.gz"
      sha256 "5046d5903174a729fd4bee377c0f358784efae2ca5560b4aaf03f7729c24c4b2"

      def install
        bin.install "albconv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okkun-sh/albconv/releases/download/v0.1.0/albconv_Linux_arm64.tar.gz"
      sha256 "595a2a3deae728708814dbb253b29d4b4dcd13a88b52f9340363b4ea5a383655"

      def install
        bin.install "albconv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/okkun-sh/albconv/releases/download/v0.1.0/albconv_Linux_x86_64.tar.gz"
      sha256 "1233d2be4ff344894f1a9296ff71385b6ae31d886bd033355dbb537bbb41db64"

      def install
        bin.install "albconv"
      end
    end
  end
end
